export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001835",
        "primary-dim": "#00d4ec",
        "surface-dim": "rgb(var(--color-surface) / <alpha-value>)",
        "inverse-on-surface": "#565555",
        "secondary-fixed-dim": "#58e7ab",
        "tertiary-fixed": "#80b2ff",
        "inverse-surface": "#fcf9f8",
        "surface-container-lowest":
          "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "primary-container": "#00e3fd",
        "surface-container-highest":
          "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "surface-container":
          "rgb(var(--color-surface-container) / <alpha-value>)",
        "on-secondary-fixed-variant": "#006544",
        "primary-fixed": "#00e3fd",
        "on-secondary-container": "#e1ffec",
        "error-container": "#9f0519",
        "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
        "on-primary": "#005762",
        "secondary-dim": "#58e7ab",
        "tertiary-fixed-dim": "#65a4ff",
        "on-primary-container": "#004d57",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "primary-fixed-dim": "#00d4ec",
        "on-secondary-fixed": "#00452d",
        "secondary-container": "#006c49",
        "surface-tint": "#81ecff",
        "secondary-fixed": "#69f6b8",
        tertiary: "#70aaff",
        outline: "#767575",
        "on-primary-fixed": "#003840",
        "surface-container-high":
          "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "tertiary-container": "#599cf9",
        background: "rgb(var(--color-background) / <alpha-value>)",
        error: "#ff716c",
        "inverse-primary": "#006976",
        "error-dim": "#d7383b",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-secondary": "#005a3c",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "on-primary-fixed-variant": "#005762",
        "on-surface-variant":
          "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-surface) / <alpha-value>)",
        secondary: "#69f6b8",
        primary: "#81ecff",
        "surface-container-low":
          "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "on-error": "#490006",
        "on-tertiary-fixed-variant": "#003971",
        "tertiary-dim": "#5c9ffc",
        "on-error-container": "#ffa8a3",
        "on-tertiary-container": "#001d3f",
        "on-tertiary": "#002a55",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Manrope"],
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-delayed": "float 6s ease-in-out infinite 2s",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(20px)" },
        },
      },
    },
  },
  plugins: [],
};
